### ISSUE TITLE
enable ci for online docs

### ISSUE THREAD

**Issue by cpaniaguam** [brown-ccv/Chamber.jl#16]
# Steps

1. Create ssh keys
```julia
julia> using DocumenterTools
julia> using DocumenterTools
julia> DocumenterTools.genkeys(user="MyUser", repo="MyPackage.jl") # update as necesarry
```
2. On github:
a) Settings >  deploy keys > add deploy key, name it Documenter, paste in the deploy key from step 1
b) Settings > secrets > actions> new repository secret > name it DOCUMENTER_KEY paste in the documenter key from step 1

3. In the package's root directory create the `.github/workflows/documentation.yml` file and add the following (might need to adjust branch name and julia version):

```yaml
name: Documentation

on:
  push:
    branches:
      - master # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7.3' # update as necessary
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl
```

4. Create the file `.github/workflows/doc-preview-cleanup.yml`:
```yaml
name: Doc Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  doc-preview-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Delete preview and history + push changes
        run: |
            if [ -d "previews/PR$PRNUM" ]; then
              git config user.name "Documenter.jl"
              git config user.email "documenter@juliadocs.github.io"
              git rm -rf "previews/PR$PRNUM"
              git commit -m "delete preview"
              git branch gh-pages-new $(echo "delete history" | git commit-tree HEAD^{tree})
              git push --force origin gh-pages-new:gh-pages
            fi
        env:
            PRNUM: ${{ github.event.number }}
```
5.  Go to the repo setttings. Under Pages on the left do:
	Source: Deploy from a branch
	Branch: gh-pages /(root) (gh-pages to be created automatically)

6. Update repo's README.md with links to documentation
